# Generated by Django 3.1.2 on 2022-01-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('years_of_warranty', models.PositiveIntegerField(default=1)),
                ('finanace_plan', models.CharField(default='unavailable', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstApp.carplan'),
        ),
    ]
