# Generated by Django 3.1.2 on 2022-01-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20220103_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
        migrations.DeleteModel(
            name='CarPlan',
        ),
    ]
